use_frameworks!

platform :ios, '9.0'

target 'DebugTool_Example' do
  pod 'DebugTool', :path => '../'

  target 'DebugTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
